# Generated by Django 5.1.3 on 2025-04-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_phone_number_user_phone_user_wilaya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='wilaya',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
