# Generated by Django 5.1.3 on 2025-04-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items_data',
            field=models.JSONField(default=list),
        ),
    ]
