# Generated by Django 5.1.3 on 2025-05-01 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0009_alter_notification_order_id_alter_notification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
