# Generated by Django 5.1.3 on 2025-05-02 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0013_wishlist'),
        ('admin_dashboard', '0015_product_stock_quantity'),
    ]

    operations = [
    ]
