# Generated by Django 5.1.3 on 2025-05-04 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0016_merge_0013_wishlist_0015_product_stock_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
