# Generated by Django 5.1.3 on 2025-05-04 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0011_productimage'),
        ('admin_dashboard', '0019_cart_cartitem'),
    ]

    operations = [
    ]
