# Generated by Django 5.1.3 on 2025-05-06 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0020_merge_0011_productimage_0019_cart_cartitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ORDER_STATUS', 'Order Status Update'), ('GENERAL', 'General Notification'), ('PROMOTION', 'Promotion')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
